#!/bin/bash

root=$(lsblk -f | grep -i root | grep -v loop | awk "{print \$1}" | cut -c 7-)
home=$(lsblk -f | grep -i home | grep -v loop | awk "{print \$1}" | cut -c 7-)

if [ "$1" != "part2" ]; then
    if [ "$1" = "wipehome" ]; then
        mkfs.ext4 -F -L home /dev/$home
    fi

    mkfs.ext4 -F -L root /dev/$root
    mount /dev/disk/by-label/root /mnt
    mkdir /mnt/home
    mount /dev/disk/by-label/home /mnt/home

    basestrap /mnt base base-devel linux-zen linux-firmware \
                   openrc elogind-openrc xorg pulseaudio    \
                   dhcpcd connman-openrc wpa_supplicant     \
                   grub os-prober ntfs-3g doas man zsh vim  \
                   bspwm rofi feh sxhkd python python-pip   \
                   git htop neofetch p7zip figlet wget mpv  \
                   youtube-dl ffmpeg pavucontrol xclip go   \
                   imagemagick gparted obs-studio

    fstabgen -U /mnt >> /mnt/etc/fstab

    cp artixinstaller /mnt/
    chmod +x /mnt/artixinstaller

    if [ "$1" != "wipehome" ]; then
        artix-chroot /mnt ./artixinstaller part2 wipedhome
    else
        artix-chroot /mnt ./artixinstaller part2
    fi
else
    useradd -m a
    echo -n a:a | chpasswd
    echo -n root:a | chpasswd

    echo "permit nopass a" > /etc/doas.conf

    chmod +w /etc/sudoers
    echo -n "a ALL=(ALL) NOPASSWD: ALL" >> /etc/sudoers

    cd /home/a/
    if [ "$2" != "wipedhome" ]; then
        rm -rf ./* ./.*
        sudo -u a git clone https://github.com/zsadroh/dotfiles .
        sudo -u a mkdir Downloads Desktop Pictures
    fi

    sudo -u a mkdir Sources
    cd Sources

    sudo -u a git clone https://github.com/zsadroh/scripts .
    ln -s file /cursors /usr/local/bin/
    ln -s file /rofifan /usr/local/bin/
    ln -s file /togif /usr/local/bin/
    ln -s file /xwal /usr/local/bin/
    chmod a+x /usr/local/bin/cursors
    chmod a+x /usr/local/bin/rofifan
    chmod a+x /usr/local/bin/togif
    chmod a+x /usr/local/bin/xwal
    rm LICENSE

    sudo -u a git clone https://aur.archlinux.org/pikaur.git
    cd pikaur
    yes | sudo -u a makepkg -fsri
    cd ..
    rm -rf pikaur/

    sudo -u a git clone https://github.com/Earnestly/sx
    cd sx
    make install
    cd ..
    rm -rf sx

    yes | sudo -u a pikaur -S --noedit rust-nightly-bin librewolf-bin    \
                                       alacritty-ligatures-git iftop-git \
                                       gallery-dl spacefm btop-git cava  \
                                       sxiv-git xwinwrap-git wavemon-git \
                                       cmatrix-git nerd-fonts-complete   \
                                       downgrade figlet-fonts            \
                                       testdisk-wip flameshot-git        \
                                       barrier-bin xdotool-git           \
                                       fontpreview-git

    pip install pywal colorthief colorz haishoku

    sudo -u a go get github.com/thefryscorer/schemer2
    mv go/bin/schemer2 /usr/local/bin
    rm -rf go
    rm -rf /home/a/go

    sudo -u a git clone https://github.com/elkowar/eww
    cd eww
    cargo build --release
    chmod a+x target/release/eww
    mv target/release/eww /usr/local/bin/
    cd ..
    rm -rf eww

    wget https://apprepo.de/appimage/download/gimp
    mv gimp /usr/local/bin/
    chmod a+x /usr/local/bin/gimp

    wget https://github.com/Swordfish90/cool-retro-term/releases/download/1.1.1/Cool-Retro-Term-1.1.1-x86_64.AppImage
    mv Cool-Retro-Term-1.1.1-x86_64.AppImage /usr/local/bin/coolretroterm
    chmod a+x /usr/local/bin/coolretroterm

    sudo -u a git clone https://github.com/preservim/nerdtree.git ~/.vim/pack/vendor/start/nerdtree
    sudo -u a vim -u NONE -c "helptags ~/.vim/pack/vendor/start/nerdtree/doc" -c q

    sudo -u a git clone https://github.com/Yggdroot/indentLine.git ~/.vim/pack/vendor/start/indentLine
    sudo -u a vim -u NONE -c "helptags  ~/.vim/pack/vendor/start/indentLine/doc" -c "q"

    ln -sf /usr/share/zoneinfo/America/Nuuk /etc/localtime
    hwclock --systohc

    echo -e "en_US.UTF-8 UTF-8\nen_US ISO-8859-1" >> /etc/locale.gen
    locale-gen
    echo -e "export LANG=\"en_US.UTF-8\"\nexport LC_COLLATE=\"C\"" >> /etc/locale.conf

    echo -n artix > /etc/hostname
    echo -n "hostname=\"artix\"" > /etc/conf.d/hostname
    echo -e "127.0.0.1 localhost\n::1 localhost\n127.0.1.1 artix" >> /etc/hosts

    echo "permit persist a" > /etc/doas.conf
    echo "permit nopass a cmd chmod args a+w /sys/class/backlight/intel_backlight/brightness" >> /etc/doas.conf

    grub-install /dev/sda
    echo "GRUB_DISABLE_OS_PROBER=false" >> /etc/default/grub
    update-grub

    mkdir /mnt/usb1 /mnt/usb2 /mnt/usb3 /mnt/usb4 /mnt/sdcard

    echo 'agetty_options="--autologin a --noclear"' > /etc/conf.d/agetty-autologin
    cd /etc/init.d
    openrc-init delete agetty.tty
    mv agetty.tty1 agetty-autologin.tty1 
    rc-update add agetty-autologin.tty1 default

    echo 'options thinkpad_acpi fan_control=1' > /etc/modprobe.d/thinkpad_acpi.conf

    sudo -u a sh -c "$(curl -fsSL https://raw.github.com/ohmyzsh/ohmyzsh/master/tools/install.sh)"

    echo -e 'if [[ -z "$DISPLAY" ]] && [[ $(tty) = /dev/tty1 ]]; then\n    sx\n    logout\nfi' >> /etc/zsh/zprofile

    echo "export ZDOTDIR=/home/a/.config/zsh/" > /etc/zsh/zshenv

    pacman -R -noconfirm sudo

    exit
fi
